export const SOCKET_ACTION_CONNECTING = "SOCKET_ACTION_CONNECTING";
export const SOCKET_ACTION_IDLE = "SOCKET_ACTION_IDLE";

export const SOCKET_STATUS_CLOSED = "SOCKET_STATUS_CLOSED";
export const SOCKET_STATUS_ERROR = "SOCKET_STATUS_ERROR";
export const SOCKET_STATUS_OPEN = "SOCKET_STATUS_OPEN";
