export const PREPARE_TURN = "PREPARE_TURN";
export const TOGGLE_DEMIURG_COLLAPSED = "TOGGLE_DEMIURG_COLLAPSED";
export const TOGGLE_EVENTS_COLLAPSED = "TOGGLE_EVENTS_COLLAPSED";
export const TOGGLE_LEVERAGE = "TOGGLE_LEVERAGE";
export const ENABLE_TRY_PAY_DEBTS = "ENABLE_TRY_PAY_DEBTS";
